snowflake-db-testing:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: kz56314.us-east-2.aws

      # User/password auth
      user: ECHAVEZM
      password: Dbttraining2022

      role: ACCOUNTADMIN
      database: ANALYTICS
      warehouse: COMPUTE_WH
      schema: DBT_MODELS
      threads: 2
      client_session_keep_alive: False
      #query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false